let suggestions = [
"Perfume",
  "iphone",
  "9",
  "IPhone X",
  "IPhone 9",
  "Phone",
  "Laptop",
  "Universe",
  "Samsung",
  "Samsung Universe",
  "Oppof19",
  "Oppo",
  "Huawei P30",
  "Huawei",
  "MacBook",
  "MacBook Pro",
  "Mac",
  "Samsung Galaxy Book",
  "Microsoft",
  "Microsoft Surface",
  "Microsoft Surface Laptop 4",
  "Infinix Inbook",
  "Inbook",
  "Infinix",
  "HP",
  "HP Pavilion",
  "Perfume Oil",
  "Brown Oil",
  "Oil",
  "Brown",
  "Fog",
  "Fog Scent",
  "Fog Xpressio",
  "Non-alcoholic",
  "Eau De Perfume",
  "Perfume Spray",
  "Hyaluronic Acid",
  "Serum",
  "Tree Oil",
  "Moisturizer",
  "Oil Free Moisturizer",
  "Skin Beauty Serum",
  "Freckle Treatment Cream",
  "Cream",
  "Daal",
  "Masoor Dal",
  "Elbow Macaroni",
  "Macaroni",
  "Orange Essence",
  "Essence",
  "Food",
  "Cereals",
  "Muesli",
  "Fruit Nuts",
  "Gulab",
  "Gulab powder",
  "Plant Hanger",
  "Hanger",
  "Flying Wooden Bird",
  "Wooden Bird",
  "3D Lamp",
  "Embellishment Art Lamp",
  "Handcraft Chinese Style",
  "Chinese Handcraft",
  "Handcraft",
  "Holder",
  "Key Holder",
  ];